name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: enriikke/gatsby-gh-pages-action@v2.1.1
      with:
        access-token: eb19b393f3b604ebf12cd5bb9779595960150a73
    - name: Run a build script
      run: npm run build
